# This defines a Github action that can be run from other repos
name: 'Canal E2E Tests'
description: 'Run end to end tests for the Canal ecosystem'
branding:
  icon: 'play'
  color: 'green'
inputs:
  browser-name:
    description: 'The browser against which to run tests, defaults to all if not provided'
    required: false
    default: 'all'
outputs:
  test-runner:
    description: 'Output from Playwright'
    value: ${{ steps.test-runner.outputs.test-output }}
runs:
  using: 'composite'
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 14
    - uses: c-hive/gha-yarn-cache@v1
    - run: yarn install
    - run: npx playwright install-deps ${{ matrix.browser }}

    # Directly runs the `yarn test` for this browser and return the value
    - id: test-runner
      run: echo "::set-output name=test-output::$(yarn test --browserName=${{ inputs.browser-name }})"
      shell: bash
