# This defines a Github action that can be run from other repos
name: 'Canal E2E Tests'
description: 'Run end to end tests for the Canal ecosystem'
branding:
  icon: 'play'
  color: 'green'
inputs:
  browser:
    description: 'The browser against which to run tests, defaults to all if not provided'
    required: false
    default: 'all'
  shard:
    description: 'The test shard so we can execute only part at a time. Will be 1/3 or 4/7, etc. Defaults to 1/1'
    required: false
    default: '1/1'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.browser }}'
    - '${{ inputs.shard }}'
