# This defines a Github action that can be run from other repos
name: 'Canal E2E Tests'
description: 'Run end to end tests for the Canal ecosystem'
branding:
  icon: 'play'
  color: 'green'
inputs:
  browser:
    description: 'The browser against which to run tests, defaults to all if not provided'
    required: false
    default: 'all'
outputs:
  test-runner:
    description: 'Output from Playwright'
runs:
  using: 'node12'
  main: 'dist/index.js'
