# Runs tests on all browsers on pushes (to any branch)
name: E2E
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Each of these are browser names we want to run tests against in parallel - Firefox is disabled until https://github.com/microsoft/playwright/issues/13027 is resolved
        browser: ['chromium', 'webkit']
        # We split tests into 4 different shards to run in parallel for speed
        shard: [1, 2, 3, 4]
    steps:
      - uses: actions/checkout@v2

      # Uses the internal Github action for testing the tester!
      - uses: ./
        name: test ${{ matrix.browser }} [${{ matrix.shard }}/4]
        env:
          APP_TEST_PASSWORD: ${{ secrets.APP_TEST_PASSWORD }}
          E2E_DATA_SETUP_URL: ${{ secrets.E2E_DATA_SETUP_URL }}
        with:
          browser: ${{ matrix.browser }}
          shard: '${{ matrix.shard }}/4'
