# Runs tests on all browsers on pushes (to any branch)
name: E2E
on:
  - push
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Each of these are browser names we want to run tests against in parallel
        browser: ['chromium', 'webkit']
    steps:
      - uses: actions/checkout@v2

      # Uses the internal Github action for testing the tester!
      - uses: ./
        name: test ${{ matrix.browser }}
        env:
          APP_TEST_PASSWORD: ${{ secrets.APP_TEST_PASSWORD }}
          E2E_DATA_SETUP_URL: ${{ secrets.E2E_DATA_SETUP_URL }}
        with:
          browser: ${{ matrix.browser }}
